matrix:
  include:
  - os: linux
    sudo: required
  - os: osx
  - os: windows
cache:
  yarn: true
branches:
  - platforms
language: node_js
notifications:
  email: false
node_js:
  - "8"
install:
  - npm install
script:
   - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run package-win;
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-linux;
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-mac;
  - npm run dist