matrix:
  include:
  - os: linux
    sudo: required
  - os: osx
cache:
  yarn: true
branches:
  - platforms
language: node_js
notifications:
  email: false
node_js:
  - "8"
install:
  - npm install
script:
  - npm run dist