matrix:
  include:
  - os: linux
    sudo: required
  - os: osx
  - os: windows
directories:
  - node_modules
branches:
  - platforms
language: node_js
notifications:
  email: false
node_js:
  - "8"
install:
  - npm install
script:
  - if ["$TRAVIS_OS_NAME" == "windows"]; then npm run package-win; fi
  - if ["$TRAVIS_OS_NAME" == "linux"]; then npm run package-linux; fi
  - if ["$TRAVIS_OS_NAME" == "osx"]; then npm run package-mac; fi
  