matrix:
  include:
  - os: linux
    sudo: required
  - os: osx
  - os: windows
branches:
  - platforms
language: node_js
notifications:
  email: false
node_js:
  - "8"
install:
  - npm install
script:
  - npm run package-win
  - npm run package-linux
  - npm run package-mac
  - npm run dist